publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }

    repositories {
        maven {
            name = 'gtodysseyRepository'
            url = 'https://maven.gtodyssey.com/releases'
            credentials {
                username = findProperty('gtodysseyRepositoryUsername')
                password = findProperty('gtodysseyRepositoryPassword')
            }
        }
        // Add repositories to publish to here.
        maven {
            credentials {
                username = System.getenv("MAVEN_USER")
                password = System.getenv("MAVEN_PASSWORD")
            }
        }
    }
}

gtoPublish {
    publishMaven = true
    publishGithub = true
    publishCurseforge = true

    mavenRepoUrl = 'releases'

    minecraftVersion = '26.1.2'
    modLoader = 'NeoForge'

    githubRepo = 'wanggugu197/Simple-Block-Game'

    curseforgeProjectId = '1555589'
    curseforgeJavaVersion = 'Java 25'
}
