org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

systemProp.https.protocols=TLSv1.2,TLSv1.3

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.71
neo_version_range=[26.1.2,)
loader_version_range=[4,)

mod_version=2.8.0
mod_id=simple_block_game
mod_name=Simple-Block-Game
mod_description=
mod_url=
mod_issue_tracker=
mod_authors=maple197
mod_license=GNU Lesser General Public License version 3